# -*- coding: utf-8 -*-
"""Data_Visualization_Final_project_(ph).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRZThqrJDWs9rOh66GWjqerxkb7C46g7
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
df = pd.read_csv('/content/drive/MyDrive/dataset/world-happiness-report (1).csv')

df.head()

df.columns = df.columns.str.lower().str.replace(' ', '_')

print("Standardized Column Names:")
print(df.columns)
print("\nDataFrame with Standardized Column Names:")
print(df.head())

df.sort_values(["country_name", "year"], inplace=True)

df.update(df.groupby("country_name").apply(lambda group: group.interpolate(method='linear', limit_direction='both')).reset_index(drop=True))

df.isnull().sum()

df.describe()

sns.set(style="darkgrid")

plt.figure(figsize=(10,6))
sns.histplot(data=df, x='life_ladder', bins=30, kde=True, color='Purple')
plt.title("Distribution of Happiness Score Across Countries", fontsize=14)
plt.xlabel("Happiness Score", fontsize=10)
plt.ylabel("Frequency", fontsize=10)
plt.tight_layout()
plt.show()

df_latest = df.loc[df.groupby('country_name')['year'].idxmax()]

df_sorted = df_latest.sort_values(by = 'life_ladder', ascending = False)

top_10_happiest_countries = df_sorted.head(10)
top_10_happiest_countries['Category'] = 'Top 10 Happiest'

bottom_10_happiest_countries = df_sorted.tail(10)
bottom_10_happiest_countries['Category'] = 'Bottom 10 Happiest'

plot_data = pd.concat([top_10_happiest_countries, bottom_10_happiest_countries])

chart = alt.Chart(plot_data).mark_bar().encode(
    x=alt.X('life_ladder', title='Happiness Score'),
    y=alt.Y('country_name', sort='-x', title='Country'),
    color=alt.Color('Category', scale=alt.Scale(range=['green', 'red']), legend=alt.Legend(title="Category")),
    tooltip=['country_name', 'life_ladder', 'Category']
).properties(
    title='Top and Bottom 10 Happiest Countries by Life Ladder Score (Latest Year)'
)
plt.figure(figsize=(10,6))
chart.show()

df_latest = df.loc[df.groupby('country_name')['year'].idxmax()]

happiness_indicator = 'life_ladder'
other_indicators = [
    'log_gdp_per_capita',
    'social_support',
    'healthy_life_expectancy_at_birth',
    'freedom_to_make_life_choices',
    'generosity',
    'perceptions_of_corruption'
]

correlation_matrix = df_latest[[happiness_indicator] + other_indicators].corr()
print("Correlation Matrix:")
print(correlation_matrix)

for indicator in other_indicators:
    plt.figure(figsize=(8, 6))
    sns.scatterplot(data=df_latest, x=indicator, y=happiness_indicator)
    plt.title(f'Correlation between {happiness_indicator.title()} and {indicator.title()}')
    plt.xlabel(indicator.title())
    plt.ylabel(happiness_indicator.title())
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

latest_year = df['year'].max()

start_year = latest_year - 4
years_to_analyze = range(start_year, latest_year + 1)

df_latest_year = df[df['year'] == latest_year].sort_values(by='life_ladder', ascending=False)

top_5_countries = df_latest_year.head(5)['country_name'].tolist()

df_top_5_trends = df[
    (df['country_name'].isin(top_5_countries)) &
    (df['year'].isin(years_to_analyze))]

plt.figure(figsize=(10, 7))
sns.lineplot(data=df_top_5_trends, x='year', y='life_ladder', hue='country_name', marker='o')
plt.title(f'Happiness Trends for Top 5 Countries ({start_year}-{latest_year})')
plt.xlabel('Year')
plt.ylabel('Happiness Score (Life Ladder)')
plt.xticks(years_to_analyze)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Country', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

import plotly.express as px
fig = px.choropleth(df, locations = "country_name", locationmode="country names", color ="life_ladder", color_continuous_scale="Reds", title="Happiness Score Across Countries")
fig.show()

gdp_per_capita_indicator = 'log_gdp_per_capita'
happiness_indicator = 'life_ladder'

correlation = df_latest[gdp_per_capita_indicator].corr(df_latest[happiness_indicator])
print(f"Correlation between {gdp_per_capita_indicator.title()} and {happiness_indicator.title()}: {correlation:.4f}")

plt.figure(figsize=(10, 7))
sns.regplot(data=df_latest, x=gdp_per_capita_indicator, y=happiness_indicator, scatter_kws={'alpha':0.6})

plt.title(f'Relationship between {gdp_per_capita_indicator.title()} and {happiness_indicator.title()} (Latest Year)')
plt.xlabel(gdp_per_capita_indicator.title())
plt.ylabel(happiness_indicator.title())

plt.grid(True, linestyle='--', alpha=0.7)

plt.show()

continent_mapping = {
    "Afghanistan": "Asia", "Albania": "Europe", "Algeria": "Africa",
    "Argentina": "South America", "Australia": "Oceania", "Austria": "Europe",
    "Bangladesh": "Asia", "Belgium": "Europe", "Brazil": "South America",
    "Canada": "North America", "China": "Asia", "Colombia": "South America",
    "Egypt": "Africa", "France": "Europe", "Germany": "Europe",
    "India": "Asia", "Indonesia": "Asia", "Iran": "Asia", "Italy": "Europe",
    "Japan": "Asia", "Kenya": "Africa", "Mexico": "North America",
    "Nigeria": "Africa", "Russia": "Europe", "Saudi Arabia": "Asia",
    "South Africa": "Africa", "Spain": "Europe", "Turkey": "Asia",
    "United Kingdom": "Europe", "United States": "North America",
    "Vietnam": "Asia"
}
df["Continent"] = df["country_name"].map(continent_mapping)

avg_happiness = df.groupby("Continent")["life_ladder"].mean()

plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.boxplot(x="Continent", y="life_ladder", data=df)
plt.xticks(rotation=45)
plt.title("Happiness Score Distribution (Box Plot)")

plt.subplot(1, 2, 2)
avg_happiness.plot(kind="bar")
plt.title("Average Happiness Score by Continent")
plt.xlabel("Continent")
plt.ylabel("Average Happiness Score")

plt.tight_layout()
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler


features = ["log_gdp_per_capita", "social_support", "healthy_life_expectancy_at_birth",
            "freedom_to_make_life_choices", "generosity", "perceptions_of_corruption",
            "positive_affect", "negative_affect"]
target = "life_ladder"

df = df.dropna(subset=[target] + features)

X = df[features]
y = df[target]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = LinearRegression()
model.fit(X_scaled, y)

feature_importance = np.abs(model.coef_)

plt.figure(figsize=(10, 5))
plt.barh(features, feature_importance, color="maroon")
plt.xlabel("Feature Importance")
plt.ylabel("Indicators")
plt.title("Feature Contribution to Happiness Score")
plt.gca().invert_yaxis()
plt.show()

df_latest = df.loc[df.groupby('country_name')['year'].idxmax()]

df_sorted = df_latest.sort_values(by = 'life_ladder', ascending = False)

top_10_happiest_countries = df_sorted.head(10)

bottom_10_happiest_countries = df_sorted.tail(10)

plot_data = pd.concat([top_10_happiest_countries, bottom_10_happiest_countries])

chart = alt.Chart(plot_data).mark_bar().encode(
    x=alt.X('life_ladder', title='Happiness Score'),
    y=alt.Y('country_name', sort='-x', title='Country'),
    color=alt.Color('Category', scale=alt.Scale(range=['green', 'red']), legend=alt.Legend(title="Category")),
    tooltip=['country_name', 'life_ladder', 'Category']
).properties(
    title='Top and Bottom 10 Happiest Countries by Life Ladder Score (Latest Year)'
)

import numpy as np
from sklearn.linear_model import LinearRegression

df = df[['life_ladder', 'perceptions_of_corruption', 'year']].dropna()

plt.figure(figsize=(10, 6))
sns.regplot(x=df['perceptions_of_corruption'], y=df['life_ladder'], scatter_kws={'alpha':0.5})
plt.xlabel("perceptions_of_corruption")
plt.ylabel("Happiness (life_ladder)")
plt.title("Happiness vs. Corruption Perception")

plt.show()

df_grouped = df.groupby("year")["life_ladder"].mean().reset_index()

X = df_grouped["year"].values.reshape(-1, 1)
y = df_grouped["life_ladder"].values
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)

plt.figure(figsize=(10, 6))
plt.scatter(df_grouped["year"], df_grouped["life_ladder"], label="Actual Data")
plt.plot(df_grouped["year"], y_pred, color="red", linestyle="--", label="Trendline")
plt.xlabel("Year")
plt.ylabel("Average Happiness (Life Ladder)")
plt.title("Trend of Happiness Over Time")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/content/drive/MyDrive/dataset/world-happiness-report (1).csv')
df.columns = df.columns.str.lower().str.replace(' ', '_')


features = ['log_gdp_per_capita', 'social_support', 'healthy_life_expectancy_at_birth']
df = df[['country_name'] + features].dropna()

scaler = StandardScaler()
scaled_features = scaler.fit_transform(df[features])

num_clusters = 4
kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(scaled_features)

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['log_gdp_per_capita'], y=df['social_support'], hue=df['Cluster'], palette='bright')
plt.xlabel("GDP per capita (Log)")
plt.ylabel("Social Support")
plt.title("Clustering of Countries Based on Happiness Factors")
plt.legend(title="Cluster")
plt.show()

fig = px.scatter_3d(df, x='log_gdp_per_capita', y='social_support', z='healthy_life_expectancy_at_birth',
                     color='Cluster', hover_data=['country_name'], title="3D Clustering of Countries")
fig.show()

import plotly.express as px
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/dataset/world-happiness-report (1).csv')
df.columns = df.columns.str.lower().str.replace(' ', '_')

df = df[['country_name', 'year', 'life_ladder']].dropna()
df = df[df['year'] >= df['year'].max() - 4]

fig = px.choropleth(df,
                     locations="country_name",
                     locationmode="country names",
                     color="life_ladder",
                     hover_name="country_name",
                     animation_frame="year",
                     color_continuous_scale="plasma",
                     title="Global Happiness Trend Over the Last Five Years")

fig.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load and prepare data
df = pd.read_csv('/content/drive/MyDrive/dataset/world-happiness-report (1).csv')
df.columns = df.columns.str.lower().str.replace(' ', '_')
df_latest = df.loc[df.groupby('country_name')['year'].idxmax()]

sns.set_style("whitegrid")
plt.figure(figsize=(15, 10))


# 1. Top/Bottom 10 Countries
plt.subplot(2, 2, 1)
top_bottom = pd.concat([
    df_latest.nlargest(10, 'life_ladder'),
    df_latest.nsmallest(10, 'life_ladder')
])
sns.barplot(data=top_bottom, y='country_name', x='life_ladder',
            hue=top_bottom.index <= 9, palette={True: 'green', False: 'red'},
            dodge=False)
plt.title('Top 10 (Green) vs Bottom 10 (Red) Countries')
plt.xlabel('Happiness Score')
plt.ylabel('')
plt.axvline(x=df_latest['life_ladder'].median(), color='gray', linestyle='--')

# 2. Happiness Distribution
plt.subplot(2, 2, 2)
sns.histplot(df_latest['life_ladder'], bins=20, kde=True, color='purple')
plt.title('Global Happiness Distribution')
plt.xlabel('Happiness Score')
plt.ylabel('Number of Countries')

# 3. Correlation Heatmap
plt.subplot(2, 2, 3)
corr_matrix = df_latest[['life_ladder', 'log_gdp_per_capita', 'social_support',
                        'healthy_life_expectancy_at_birth', 'freedom_to_make_life_choices']].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Factor Correlations with Happiness')

# 4. GDP vs Happiness
plt.subplot(2, 2, 4)
sns.regplot(data=df_latest, x='log_gdp_per_capita', y='life_ladder',
            scatter_kws={'alpha':0.5}, line_kws={'color':'red'})
plt.title('GDP per Capita vs Happiness')
plt.xlabel('Log GDP per Capita')
plt.ylabel('Happiness Score')

plt.tight_layout()
plt.suptitle('World Happiness Dashboard', y=1.02, fontsize=16)
plt.show()